chore: fixes rag sample
firebase/genkit pull request #1048
Opened 2024-10-13 21:04 UTC by pavelgj

2024-10-13 21:15 UTC, tonybaroneee approved these changes

2024-10-13 21:16 UTC, pavelgj commented on js/testapps/rag/package.json
> +    "genkit:dev": "GENKIT_ENV=dev pnpm dev",
```suggestion
    "genkit:dev": "cross-env GENKIT_ENV=dev pnpm dev",
```

2024-10-14 15:33 UTC, tonybaroneee requested changes

2024-10-14 15:33 UTC, tonybaroneee commented on js/testapps/rag/package.json
> +    "dev": "tsx --watch src/index.ts",
I think you'll need to add `tsx` as a dev dep now as well

2024-10-14 17:42 UTC, tonybaroneee approved these changes

2024-10-14 17:43 UTC, merged