Update evals docs
firebase/genkit pull request #1394
Opened 2024-11-25 19:47 UTC by ssbushi

Fix #1391 

Checklist (if applicable):
- [ ] Docs updated

2024-11-25 21:53 UTC, chrisraygill requested changes
In samples, it's unclear where the `ai` instance, `z`, and potentially other imports are coming from.

2024-11-25 21:53 UTC, chrisraygill commented on docs/evaluation.md
On line 261:

```ts
filePath = path.resolve(filePath);
```

Does `path` need to be imported?

2024-11-25 21:53 UTC, chrisraygill commented on docs/evaluation.md
On line 262:

```ts
const pdfTxt = await run("extract-text", () => extractText(filePath));
```

Does `exractText` need to be imported?

2024-11-25 21:53 UTC, chrisraygill commented on docs/evaluation.md
On line 265:

```ts
chunk(pdfTxt, chunkingConfig)
```

Where does `chunkingConfig` come from?

2024-11-25 21:56 UTC, chrisraygill reviewed
on line 128, should `defineEvaluator` be `ai.defineEvaluator` ?

2024-11-25 22:06 UTC, chrisraygill commented on docs/plugin-authoring-evaluator.md
> +  testCaseId: z.string(),
`testCaseId` is duplicated in the schema

2024-11-25 22:06 UTC, chrisraygill approved these changes

2024-11-26 15:18 UTC, pavelgj commented
please follow https://www.conventionalcommits.org/en/v1.0.0/ for PRs

2024-11-27 15:35 UTC, ssbushi commented on docs/evaluation.md
It's a custom method, we cover this in our RAG documentation. I've added a comment here. LMK if that is not sufficient.

2024-11-27 15:52 UTC, merged