chore: polish mult-agent example
firebase/genkit pull request #1476
Opened 2024-12-10 00:30 UTC by huangjeff5

Checklist (if applicable):
- [x] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
- [x] Tested (manually, unit tested, etc.)
- [x] Docs updated (updated docs or a docs bug required)

2024-12-11 19:15 UTC, pavelgj commented on samples/js-schoolAgent/src/routingAgent.ts
> +export const routingAgent = ai.definePrompt(
I think I prefer `infoAgent`....

2024-12-11 19:16 UTC, pavelgj commented on samples/js-schoolAgent/README.md
> +- "Mark Evenlyn Smith as absent please"
```suggestion
- "Evelyn will be late today"
```

2024-12-11 19:19 UTC, pavelgj commented on samples/js-schoolAgent/src/attendanceAgent.ts
> +${agentPrompt(specialization)}
This makes it hard to see what this agent does at a glance. I think I little duplication is OK. It makes customization easier.

2024-12-16 19:33 UTC, pavelgj approved these changes

2024-12-16 22:22 UTC, peterfriese requested changes
This is more of a walkthrough of an existing code sample, and not a hands-on codelab. 

While there is nothing wrong with a walkthrough, I would prefer giving people a hand-on experience of creating an agent system themselves, to show them how it's really done.

2024-12-16 23:19 UTC, huangjeff5 commented
> This is more of a walkthrough of an existing code sample, and not a hands-on codelab.
> 
> While there is nothing wrong with a walkthrough, I would prefer giving people a hand-on experience of creating an agent system themselves, to show them how it's really done.

Makes sense. I think it will take some more work and iteration than I initially thought, so I'm going to work on this and try to simplify it and make it more hands-on, and make a separate PR.

2024-12-16 23:41 UTC, peterfriese approved these changes
OK to merge as a sample.

2024-12-16 23:46 UTC, merged