feature(go): create model references with dynamic config
firebase/genkit pull request #1575
Opened 2024-12-26 20:08 UTC by hugoaguirre

Description here... Help the reviewer by:
 - linking to an issue that includes more details
 - if it's a new feature include samples of how to use the new feature
 - (optional if issue link is provided) if you fixed a bug include basic bug details

Checklist (if applicable):
- [ ] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
- [ ] Tested (manually, unit tested, etc.)
- [ ] Docs updated (updated docs or a docs bug required)

2025-01-04 05:03 UTC, hugoaguirre commented
Hi @pavelgj, @apascal07 

Let me know your opinion about this approach.
I wanted to keep the model definition as it previously was because I think it was very simple and verbose.

The only changes added were:
- Rewrote how the known models are defined in the plugins (adding a new struct named: `ai.ModelDetails` that encapsulates the model capabilities and its versions)
- `ai.ModelMetadata` was updated to add model versions so they can be grouped together

2025-01-08 18:39 UTC, alonsopec89 commented on go/plugins/googleai/googleai.go
> +		},
this hardcoded strings of the version management can become a bit complicated to maintain, and since we are using the same ones in googleai and vertexai, I think it would be good to have in some constants file, maybe in the genkit package or another new one, so that it is used here and in vertexai

2025-01-15 20:05 UTC, hugoaguirre commented on go/plugins/googleai/googleai.go
> +		},
Good observation @alonsopec89. 

I was looking at how things were implemented in Genkit JS and plugins are in charge of defining the models they use regardless if more plugins are using the same models. e.g. [js vertex](https://github.com/firebase/genkit/blob/main/js/plugins/vertexai/src/gemini.ts#L218) and [js googleai](https://github.com/firebase/genkit/blob/main/js/plugins/googleai/src/gemini.ts#L112).

About placing these model definitions in `genkit` package... my understanding is that Genkit should be model-agnostic so I believe that's the reason behind why plugins are defining their models on their packages.

2025-02-03 21:08 UTC, hugoaguirre commented
> How is this to be used in code? I don't see any way to reference the exact version I want to use in a generate call for example.
Feedback addressed in the last commit

2025-02-03 21:19 UTC, apascal07 commented
Overall, looks good. There's an outstanding issue that you are indirectly (but not fully) touching upon here: https://github.com/firebase/genkit/issues/1744

It's unrelated to this PR but it might make sense to just combine it, or at least do it just for the `versions` field and save the rest for another PR.

2025-02-04 17:24 UTC, apascal07 requested changes

2025-02-04 17:24 UTC, apascal07 commented on go/ai/generate.go
> +		"media":      metadata.Info.Supports.Media,
Unmarshal `ModelInfoSupports` into the map programatically so we have full coverage of fields going forward.

2025-02-04 17:24 UTC, apascal07 commented on go/ai/generate.go
> +		return false, fmt.Errorf("version not supported: %s", v)
Add a test that covers this.

2025-02-04 17:24 UTC, apascal07 commented on go/ai/generate.go
> +	a := core.LookupActionFor[*ModelRequest, *ModelResponse, *ModelResponseChunk](r, atype.Model, parts[0], parts[1])
Use `ai.LookupModel` here.

2025-02-04 17:24 UTC, apascal07 commented on go/ai/generate.go
> +		return false, errors.New("model action not defined")
`"model %s not found", model`

2025-02-04 17:30 UTC, hugoaguirre commented on go/ai/generate.go
> +	Versions []string
Fair enough, I thought we wanted to keep `ModelMetadata` as well. 
Changing it.

2025-02-04 21:49 UTC, hugoaguirre commented on go/ai/generate.go
> +		"media":      metadata.Info.Supports.Media,
For the record: After internal conversation with Alex, it was decided not to follow this suggestion since these changes will be breaking current functionality: `DefineModel` would have to check for errors during Marshal/Unmarshal process and return value must change to `(Model, error)` which will break the current state of the API.

2025-02-05 22:15 UTC, apascal07 approved these changes

2025-02-05 22:37 UTC, merged