Go docs: prompts and dotprompts
firebase/genkit pull request #472
Opened 2024-06-25 02:04 UTC by kevinthecheung

Description here... 

Checklist (if applicable):
- [ ] Tested (manually, unit tested, etc.)
- [ ] Changelog updated
- [ ] Docs updated

2024-06-25 13:39 UTC, ianlancetaylor approved these changes

2024-06-25 19:46 UTC, ianlancetaylor commented on docs-go/dotprompt.md
> +  vertexai.Init(context.Background(), projectID, "us-central1")
Better to write

    ctx := context.Background()

and then use `ctx` here and below rather than calling `context.Background` multiple times.

2024-06-25 19:46 UTC, ianlancetaylor commented on docs-go/dotprompt.md
> +  projectID := os.Getenv("GCLOUD_PROJECT")
Use the new weave program for this code?

2024-06-25 19:46 UTC, ianlancetaylor commented on docs-go/dotprompt.md
> +
Always a good idea to check errors in examples, even if you just call `log.Fatal`.

2024-06-25 19:46 UTC, ianlancetaylor commented on docs-go/dotprompt.md
> +The above schema is equivalent to the following TypeScript interface:
I'm not sure it's all that helpful for the Go docs to refer to a TypeScript interface.  Can we instead show the JSON version of the corresponding JSON schema?

2024-06-25 19:46 UTC, ianlancetaylor commented on docs-go/dotprompt.md
> +  describeImagePrompt, err := dotprompt.Open("describe_image")
Check errors.

2024-06-25 19:46 UTC, ianlancetaylor commented on docs-go/dotprompt.md
> +  dataUri := fmt.Sprintf("data:image/jpeg;base64,%s", encodedImage)
Really minor, but I would write

    dataURI := "data:image/jpeg;base64," + encodedImage

2024-06-25 21:39 UTC, jba requested changes

2024-06-25 21:39 UTC, jba commented on docs-go/dotprompt.md
> +```ts
Translate to Go.

2024-06-26 11:18 UTC, jba requested changes

2024-06-26 11:18 UTC, jba commented on go/internal/doc-snippets/prompts.go
> +		log.Fatal(err)
change these to `return err`. That's more common.

2024-06-26 17:14 UTC, jba approved these changes

2024-06-26 18:40 UTC, merged