Create code for menu/basic example
firebase/genkit pull request #57
Opened 2024-05-07 18:01 UTC by MaesterChestnut

https://github.com/firebase/genkit/issues/56

Next steps are rewriting what `genkit init` creates and incorporating the changes to the docs

2024-05-07 20:45 UTC, schnecle approved these changes

2024-05-08 16:53 UTC, maxl0rd requested changes
I think it's confusing to have this nested inside the existing sample. Could we put up a level it in it's own samples/xxxxx folder. When it supersedes the existing sample we can just remove that one?

2024-05-08 18:14 UTC, schnecle reviewed
It looks like we have menu-example/basic/basic - should that just be menu-example/basic?

2024-05-08 19:16 UTC, MichaelDoyle commented on js/samples/menu-example/basic/basic/src/index.ts
> +      Tell me if ${subject} can be found on the menu`,
I am not 💯 on how it ties in with your broader plans, but what we discussed in-person was perhaps turning this into something more creative/generative in nature, like a menu generator, or similar.

2024-05-09 13:33 UTC, maxl0rd approved these changes

2024-05-09 13:42 UTC, MichaelDoyle approved these changes

2024-05-09 13:46 UTC, merged