RAG docs for Go
firebase/genkit pull request #578
Opened 2024-07-10 19:38 UTC by kevinthecheung

Description here... 

Checklist (if applicable):
- [ ] Tested (manually, unit tested, etc.)
- [ ] Changelog updated
- [ ] Docs updated

2024-07-10 20:03 UTC, jba requested changes

2024-07-10 20:03 UTC, jba commented on go/internal/doc-snippets/rag/main.go
> +	genkit.Init(ctx, nil)
Check for returned error.

2024-07-10 20:03 UTC, jba commented on go/internal/doc-snippets/rag/main.go
> +    buf.ReadFrom(b)
Not sure what's going on here. if `b` is a []byte, then you can just do `string(b)`.

2024-07-10 20:03 UTC, jba commented on go/internal/doc-snippets/rag/main.go
> +			pdfText, err := genkit.Run(ctx, "extract", func() (string, error) {
Explain why you're using genkit.Run here instead of doing the work directly.

2024-07-10 20:03 UTC, jba commented on go/internal/doc-snippets/rag/main.go
> +				for i := range len(chunks) {
for _,c := range chunks

2024-07-10 20:03 UTC, jba commented on go/internal/doc-snippets/rag/main.go
> +				Documents: docs, Options: nil,
You can omit `Options: nil`

2024-07-10 21:09 UTC, kevinthecheung commented on go/internal/doc-snippets/rag/main.go
> +    defer f.Close()
i don't know, so i included the check

2024-07-11 00:00 UTC, jba requested changes

2024-07-11 00:00 UTC, jba commented on go/internal/doc-snippets/rag/main.go
> +				k = opts.K
OK, so the bug here (sorry, just saw it) is that someone may do

     CustomMenuRetrieverOptions{K: 5}

leaving the other option at 0, but you set both.
So a better way is to assume 0 means unset (which I think is OK for both of these options, zero doesn't make sense, right?).
Then you'd write 
   if opts.K != 0 { k = opts.K}
and similarly for the other one.

But I think here is a nicer way:
```
opts, _ := req.Options.(CustomMenuRetrieverOptions)
// If req.Options is not the right type, then opts is a zero CustomMenuRetrieverOptions.
if opts.K == 0 { opts.K = 3 }
if ... // the other one
```
Then use opts.K, etc. in the following code.

2024-07-11 22:56 UTC, ssbushi commented on docs-go/rag.md
> +- [Cloud Firestore vector store](plugins/firebase.md)
The go SDK only has pinecone support for RAG.

2024-07-11 23:10 UTC, ssbushi approved these changes

2024-07-12 18:21 UTC, jba approved these changes

2024-07-12 18:40 UTC, merged