Remove preview language from evals docs and expand supported evaluators
firebase/genkit pull request #6
Opened 2024-05-01 21:52 UTC by schnecle

2024-05-01 23:29 UTC, kevinthecheung requested changes

2024-05-01 23:29 UTC, kevinthecheung commented on docs/evaluation.md
> +## Supported Evaluator Plugins
```suggestion
## Supported evaluators
```

2024-05-01 23:29 UTC, kevinthecheung commented on docs/evaluation.md
> +Firebase Genkit supports [Langchain Criteria Evaluation](https://python.langchain.com/docs/guides/productionization/evaluation/string/criteria_eval_chain/) via the Langchain Plugin.
```suggestion
### Genkit evaluators

Genkit includes a small number of native evaluators, inspired by RAGAS, to help you get started:

- Faithfulness
- Answer Relevancy
- Maliciousness

### Evaluator plugins

Genkit supports additional evaluators through plugins:

- VertexAI Rapid Evaluators via the [VertexAI Plugin](plugins/vertex-ai#evaluation).
- [LangChain Criteria Evaluation](https://python.langchain.com/docs/guides/productionization/evaluation/string/criteria_eval_chain/) via the [LangChain plugin](plugins/langchain.md).
```

2024-05-02 12:04 UTC, schnecle commented on docs/evaluation.md
> +## Supported Evaluator Plugins
done.

2024-05-02 12:04 UTC, schnecle commented on docs/evaluation.md
> +Firebase Genkit supports [Langchain Criteria Evaluation](https://python.langchain.com/docs/guides/productionization/evaluation/string/criteria_eval_chain/) via the Langchain Plugin.
done.

2024-05-02 13:06 UTC, pavelgj approved these changes

2024-05-02 13:18 UTC, ssbushi approved these changes

2024-05-02 13:27 UTC, tagboola approved these changes

2024-05-02 17:32 UTC, kevinthecheung approved these changes

2024-05-02 18:25 UTC, merged